# Generated by Django 5.0.3 on 2024-03-16 23:09

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customauthor',
            name='date_birth',
            field=models.DateField(blank=True, null=True, validators=[account.validators.validate_age_18_or_above], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='customauthor',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1, verbose_name='Sexo'),
        ),
    ]
