# Generated by Django 5.0.3 on 2024-03-19 01:03

import django.db.models.deletion
import forum.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('category', models.CharField(choices=[('TECH', 'Tecnologia'), ('SPORTS', 'Esportes'), ('ENTERTAINMENT', 'Entretenimento'), ('POLITICS', 'Política'), ('HEALTH', 'Saúde'), ('AGRICULTURE', 'Agricultura'), ('FINANCE', 'Finanças'), ('EDUCATION', 'Educação'), ('TRAVEL', 'Viagens'), ('FOOD', 'Alimentação'), ('FASHION', 'Moda')], max_length=100, verbose_name='Categoria')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Data de Postagem')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagem_forum/', verbose_name='Imagem')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor(a)')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Data de Postagem')),
                ('message', models.TextField(validators=[forum.validators.validate_message_length], verbose_name='Mensagem')),
                ('Commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentarista')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topic', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
