# Generated by Django 5.0.3 on 2024-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
        migrations.AddField(
            model_name='topic',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Assunto'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='posts',
        ),
    ]
