# Generated by Django 5.0.3 on 2024-07-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_date_modified_topic_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
